=== Amarr7777/XML-TO-HTML-usingXSL/lab5(XML to html)/products.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" type="product_d" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="product_d">
        <xs:sequence>
            <xs:element name="id" type="xs:int" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="price" type="xs:decimal" />
            <xs:element name="description" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Amarr7777/XML-TO-HTML-usingXSL/lab5(XML to html)/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="products.xsd">
    <product>
        <id>1</id>
        <name>Laptop</name>
        <price>999.99</price>
        <description>Powerful laptop with great features.</description>
    </product>
    <product>
        <id>1</id>
        <name>Laptop</name>
        <price>999.99</price>
        <description>Powerful laptop with great features.</description>
    </product>
    <product>
        <id>1</id>
        <name>Laptop</name>
        <price>999.99</price>
        <description>Powerful laptop with great features.</description>
    </product>
</products>
